### ISSUE TITLE
"warn" and "info" are not known tasks in sbt 0.11.2

### ISSUE THREAD

**Issue by eric** [paulp/sbt-extras#147] opened 2016-04-13 00:17 UTC
When trying to use this with older versions of sbt, sbt fails with:

```
[error] Not a valid command: warn
[error] Not a valid project ID: warn
[error] Not a valid configuration: warn
[error] Not a valid key: warn (similar: run, clean, watch)
[error] warn
[error]     ^
```

**Comment by dwijnand** [comment] 2016-04-13 04:37
Duplicate of #99

**Closed** 2016-07-01 23:57 UTC
