### ISSUE TITLE
cygwin support

### ISSUE THREAD

**Issue by som-snytt** [paulp/sbt-extras#198] opened 2017-05-16 17:33 UTC
The cygpath is required only for the final java command.

I tried to revive my old cygwin enviro and downloading failed. I tried updating cygwin before submitting a PR and of course updating failed miserably. After I sort it out, I'll attempt a PR from cygwin. Old times!

**Comment by dwijnand** [comment] 2019-10-23 09:33
I don't plan on working on this, so I'm going to close it.  But the issue isn't invalid.

**Closed by dwijnand** 2019-10-23 09:33 UTC

**Comment by som-snytt** [comment] 2019-10-23 09:42
Personally, I will probably not revert to cygwin again, despite fond memories. Future goal is to avoid even using Linux subsystem under Windows. I maintain one Windows machine required for the day job, basically a terminal.
